// --------------------------------------------------------------------------------------------------
// PUBLISHED SCHEMA FIDELITY - MAKING THE GENERATED DOCUMENT SAY WHAT THE AUTHORED CONTRACT SAYS
//
// shared/PowerFramework.Contracts/OpenApi/security.v1.yaml is AUTHORITATIVE for this service's wire
// surface. The document this service serves from /openapi/v1.json is a SEPARATE artifact, generated by
// Microsoft.AspNetCore.OpenApi from the endpoint declarations and the request and response types - and a
// client generator consumes the generated one. Where the two disagree the generated one is the defect,
// because the authored one is the agreed contract.
//
// THREE STRUCTURAL PROPERTIES DIFFER IN GENERATION, AND THIS FILE RESTORES ALL THREE.
//
//   1. CLOSURE OF THIS SERVICE'S OWN SHAPES. Every one of the thirty named object schemas in the authored
//      document carries `additionalProperties: false`. That is not cosmetic: the authored JsonWebKey
//      schema states in its own description that closure is what makes the prohibition on publishing
//      private key material STRUCTURAL rather than advisory - "a private member is unrepresentable in a
//      document conforming to this schema, not merely undocumented" - and a reviewer is invited to check
//      the property by reading the schema. A generated schema that omits it silently withdraws that
//      guarantee from the artifact a consumer actually reads.
//
//   2. OPENNESS OF A SHAPE THIS SERVICE DOES NOT OWN. The authored document sets
//      `additionalProperties: true` on ProblemDetails, explicitly and alone, because RFC 9457 problem
//      details are extensible BY DESIGN and every error body this service writes carries at least the
//      retCode extension member. Closing it would publish a schema that this service's own errors
//      violate on every single failure. This has to be an ACTIVE step rather than a skip: with any schema
//      transformer registered the generator materializes every schema, and a materialized ProblemDetails
//      is emitted CLOSED unless something opens it - measured on this surface, not assumed.
//
//   3. NON-NULLABILITY, IN BOTH PLACES IT LEAKS. The crypto and issuance request shapes declare their
//      members as NULLABLE properties on purpose, so that an absent member reaches the handler and is
//      refused with a contract error naming it - E_INVALID_ARGUMENT plus the member's wire spelling -
//      rather than being refused by the binder with a message that names nothing useful. The generator
//      reads that nullability and (a) types each member as a union admitting null and (b) adds a null
//      entry to the payload-form enumeration. For members the contract REQUIRES, and which every handler
//      refuses when null, both statements are false: the authored document types the same members
//      non-nullable and lists exactly two payload forms.
//
// WHAT THIS FILE DELIBERATELY DOES NOT DO.
//
//   * It does not decide requiredness. Which members are required is declared ON THE MEMBER, with
//     [Required], in the same file as the member and beside the handler arm that enforces it - locality a
//     table in this file would destroy, and a table would then be free to drift from both the contract
//     and the handler. This transformer only reads the `required` list those declarations produced.
//   * It changes NO binding, NO validation and NO response. It edits a document. Every refusal a caller
//     can observe is produced by the handler arms, unchanged, and is asserted by the rejection-arm suite.
// --------------------------------------------------------------------------------------------------

using System.Text.Json.Nodes;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace PowerFramework.Security.Endpoints;

/// <summary>
/// What the fidelity pass did to one generated schema.
/// </summary>
/// <remarks>
/// Reported rather than inferred so a test can assert the SELECTION as well as the effect. A skipped
/// schema and an already-correct schema are indistinguishable by inspecting the result alone, so a rule
/// that stopped selecting anything would keep passing against an outcome-only assertion.
/// </remarks>
internal enum SchemaFidelityOutcome
{
    /// <summary>Not a shape either rule applies to, and left exactly as generated.</summary>
    Untouched = 0,

    /// <summary>One of this service's own object shapes: closed, and its required members denied null.</summary>
    Closed = 1,

    /// <summary>An object shape this service does not own: opened, per the authored contract.</summary>
    Opened = 2,

    /// <summary>One of this service's own enumerations: the generator's null member removed.</summary>
    EnumNarrowed = 3,
}

/// <summary>
/// Restores the structural properties the OpenAPI generator does not carry from this service's authored
/// contract into its published document: closure of this service's shapes, openness of ProblemDetails,
/// and the non-nullability of a required member.
/// </summary>
/// <remarks>
/// <para>
/// Registered as a schema transformer on the document generator. A transformer runs for EVERY schema the
/// document contains, including the sub-schema of each individual property, so the first thing every rule
/// here does is establish which kind of shape it has in hand.
/// </para>
/// <para>
/// THE ASSEMBLY TEST IS THE SCOPE BOUNDARY, AND IT IS DELIBERATELY NOT A NAME LIST. Every shape this
/// service publishes is declared in this assembly; every shape it does not own - ProblemDetails, a BCL
/// collection, a primitive - is declared elsewhere. A name list would have to be maintained in step with
/// the endpoint files and would fail silently once it fell behind, whereas the assembly test cannot fall
/// behind: a shape added to this service is inside it the moment it is declared.
/// </para>
/// </remarks>
internal static class PublishedSchemaFidelity
{
    /// <summary>
    /// Registers the fidelity transformer on the generated document.
    /// </summary>
    /// <param name="options">The generator options the transformer is added to.</param>
    /// <exception cref="ArgumentNullException"><paramref name="options"/> is <see langword="null"/>.</exception>
    internal static void Configure(OpenApiOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        options.AddSchemaTransformer(static (schema, context, _) =>
        {
            Restore(schema, context.JsonTypeInfo.Type);
            return Task.CompletedTask;
        });

        // The second pass runs over the finished document, because the one thing it fixes does not exist
        // yet while the schemas are being built. See RemoveNullChoices.
        options.AddDocumentTransformer(static (document, _, _) =>
        {
            RemoveNullChoices(document);
            return Task.CompletedTask;
        });
    }

    /// <summary>
    /// Removes the null branch from every required member published as a choice between null and a named
    /// schema.
    /// </summary>
    /// <param name="document">The finished document, mutated in place.</param>
    /// <returns>The number of members changed, so the pass is assertable rather than assumed effective.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="document"/> is <see langword="null"/>.</exception>
    /// <remarks>
    /// <para>
    /// WHY A SECOND PASS EXISTS. A nullable member that references another named schema cannot carry a
    /// sibling type, so the generator publishes it as <c>oneOf: [{type: null}, {$ref: ...}]</c> - and it
    /// builds that wrapper after every schema transformer has run. The schema pass therefore cannot see it;
    /// this one runs over the completed document, which is the first point at which it exists.
    /// </para>
    /// <para>
    /// THE SELECTION IS THE SCHEMA'S OWN REQUIRED LIST, WHICH IS WHAT MAKES THIS SAFE WITHOUT A NAME LIST.
    /// A member is touched only when the schema declaring it already names it required, so the statement
    /// being removed - "this member may be null" - is one the same schema has already contradicted. A
    /// schema with no required list, ProblemDetails included, is not visited at all.
    /// </para>
    /// <para>
    /// WHERE ONLY THE REFERENCE REMAINS, THE WRAPPER GOES WITH THE BRANCH. The member is replaced by the
    /// reference itself, which is exactly how the authored contract spells the same member - a one-element
    /// choice would be semantically identical but textually a third spelling of it. A wrapper carrying
    /// anything else of its own is trimmed rather than replaced, so no authored detail is discarded.
    /// </para>
    /// </remarks>
    internal static int RemoveNullChoices(OpenApiDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        if (document.Components?.Schemas is not { Count: > 0 } schemas)
        {
            return 0;
        }

        int changed = 0;

        foreach (IOpenApiSchema declared in schemas.Values)
        {
            if (declared is not OpenApiSchema schema ||
                schema.Required is not { Count: > 0 } required ||
                schema.Properties is not { Count: > 0 } properties)
            {
                continue;
            }

            foreach (string memberName in required)
            {
                if (properties.TryGetValue(memberName, out IOpenApiSchema? member) &&
                    TryRemoveNullChoice(properties, memberName, member))
                {
                    changed++;
                }
            }
        }

        return changed;
    }

    /// <summary>Removes the null branch from one member's choice list.</summary>
    /// <param name="properties">The declaring schema's member map, so a collapsed member can be replaced.</param>
    /// <param name="memberName">The member's name in that map.</param>
    /// <param name="member">The member's published sub-schema.</param>
    /// <returns><see langword="true"/> when a null branch was present and was removed.</returns>
    private static bool TryRemoveNullChoice(
        IDictionary<string, IOpenApiSchema> properties,
        string memberName,
        IOpenApiSchema member)
    {
        if (member is not OpenApiSchema wrapper || wrapper.OneOf is not { Count: > 0 } branches)
        {
            return false;
        }

        List<IOpenApiSchema> retained = [.. branches.Where(static branch => !IsNullBranch(branch))];

        if (retained.Count == branches.Count || retained.Count == 0)
        {
            return false;
        }

        bool wrapperCarriesNothingElse =
            wrapper.Description is null &&
            wrapper.Title is null &&
            wrapper.Default is null &&
            wrapper.Enum is null &&
            wrapper.AllOf is null &&
            wrapper.AnyOf is null;

        if (retained.Count == 1 && wrapperCarriesNothingElse)
        {
            properties[memberName] = retained[0];
            return true;
        }

        wrapper.OneOf = retained;
        return true;
    }

    /// <summary>
    /// Applies the fidelity rules to one schema.
    /// </summary>
    /// <param name="schema">The generated schema, mutated in place.</param>
    /// <param name="declaredType">The CLR type the schema was generated from.</param>
    /// <returns>What was done, so that the selection itself is assertable.</returns>
    /// <exception cref="ArgumentNullException">Either argument is <see langword="null"/>.</exception>
    internal static SchemaFidelityOutcome Restore(OpenApiSchema schema, Type declaredType)
    {
        ArgumentNullException.ThrowIfNull(schema);
        ArgumentNullException.ThrowIfNull(declaredType);

        // THE NULLABLE WRAPPER IS UNWRAPPED FIRST, AND OMITTING THIS STEP IS WHY THE ENUMERATION RULE
        // SILENTLY DID NOTHING WHEN IT WAS FIRST WRITTEN. A nullable member declared as `PayloadForm?`
        // reaches a transformer as Nullable<PayloadForm>, whose IsEnum is FALSE and whose declaring
        // assembly is the runtime's rather than this one's - so both tests below answered the wrong
        // question about the one enumeration on this surface, and the null member stayed in the published
        // list. Measured, not reasoned about: the emitted document still carried it.
        Type shapeType = Nullable.GetUnderlyingType(declaredType) ?? declaredType;

        bool isOwnShape = shapeType.Assembly == typeof(PublishedSchemaFidelity).Assembly;

        if (IsObjectShape(schema))
        {
            if (!isOwnShape)
            {
                // Rule 2. An unrequested closure is a promise this service is not entitled to make about a
                // type it does not own and cannot control across framework versions, and for the one such
                // shape on this surface the authored contract says the opposite outright.
                schema.AdditionalPropertiesAllowed = true;
                return SchemaFidelityOutcome.Opened;
            }

            // Rule 1.
            schema.AdditionalPropertiesAllowed = false;

            // Rule 3a, applied only to members the generator already listed as required, which is exactly
            // the set the [Required] declarations produced.
            if (schema.Required is { Count: > 0 } required && schema.Properties is { Count: > 0 } properties)
            {
                foreach (string memberName in required)
                {
                    if (properties.TryGetValue(memberName, out IOpenApiSchema? member))
                    {
                        DenyNull(member);
                    }
                }
            }

            return SchemaFidelityOutcome.Closed;
        }

        // Rule 3b. Only this service's own enumerations, because the null member is there for the same
        // reason - a nullable member referencing the enumeration - and the authored contract lists the
        // members without it.
        if (isOwnShape && shapeType.IsEnum && RemoveNullMember(schema))
        {
            return SchemaFidelityOutcome.EnumNarrowed;
        }

        return SchemaFidelityOutcome.Untouched;
    }

    /// <summary>
    /// Decides whether a generated schema describes an object with members.
    /// </summary>
    /// <param name="schema">The generated schema.</param>
    /// <returns><see langword="true"/> when the closure rules apply to it.</returns>
    /// <remarks>
    /// <para>
    /// It reads the GENERATED type rather than asking the CLR type whether it is a class, because a
    /// record generated as a string is what the document says it is, and closure on a string schema would
    /// be nonsense to publish.
    /// </para>
    /// <para>
    /// The properties test excludes a shape generated with no members at all. There is no such shape on
    /// this surface today; the condition is here because closing an empty schema would forbid EVERY
    /// property rather than forbidding the unknown ones, which is a far stronger statement than the
    /// authored contract makes anywhere.
    /// </para>
    /// </remarks>
    private static bool IsObjectShape(OpenApiSchema schema) =>
        schema.Type.HasValue &&
        schema.Type.Value.HasFlag(JsonSchemaType.Object) &&
        schema.Properties is { Count: > 0 };

    /// <summary>
    /// Removes null from one member's admitted types.
    /// </summary>
    /// <param name="member">The member's generated sub-schema.</param>
    /// <remarks>
    /// <para>
    /// A nullable scalar arrives as a type union - <c>["null","string"]</c> - and the null flag is cleared
    /// from it.
    /// </para>
    /// <para>
    /// THE OTHER SHAPE IS NOT REACHABLE FROM HERE, AND FINDING THAT OUT COST A ROUND OF MEASUREMENT WORTH
    /// RECORDING. A nullable reference to another named schema is published instead as
    /// <c>oneOf: [{type: null}, {$ref: ...}]</c>, because a reference cannot carry a sibling type - but the
    /// generator builds that wrapper AFTER every schema transformer has run. Observed at this point, such a
    /// member carries no type and no choice list at all, so code here that trimmed a null branch would have
    /// been dead while looking correct. It is done in the document pass instead, which is the first place
    /// the graph is complete.
    /// </para>
    /// </remarks>
    private static void DenyNull(IOpenApiSchema member)
    {
        if (member is not OpenApiSchema mutable)
        {
            return;
        }

        if (mutable.Type.HasValue && mutable.Type.Value.HasFlag(JsonSchemaType.Null))
        {
            JsonSchemaType withoutNull = mutable.Type.Value & ~JsonSchemaType.Null;

            // Guard against a member declared as null and nothing else. Clearing the flag would leave an
            // empty type, which admits everything - the opposite of what this rule is for.
            if (withoutNull != 0)
            {
                mutable.Type = withoutNull;
            }
        }
    }

    /// <summary>Decides whether one branch of a choice admits nothing but null.</summary>
    /// <param name="branch">The branch to classify.</param>
    /// <returns><see langword="true"/> when the branch is the generator's null arm.</returns>
    private static bool IsNullBranch(IOpenApiSchema branch) =>
        branch.Type.HasValue && branch.Type.Value == JsonSchemaType.Null;

    /// <summary>
    /// Removes the generator's null member from an enumeration's member list.
    /// </summary>
    /// <param name="schema">The enumeration's generated schema.</param>
    /// <returns><see langword="true"/> when a null member was present and was removed.</returns>
    /// <remarks>
    /// A missing JSON node and a node of kind null are both treated as the null member, because the two
    /// are the same statement about the enumeration and only one of them is worth depending on.
    /// </remarks>
    private static bool RemoveNullMember(OpenApiSchema schema)
    {
        if (schema.Enum is not { Count: > 0 } members)
        {
            return false;
        }

        List<JsonNode> retained = [.. members.Where(static member => member is not null && member.GetValueKind() != System.Text.Json.JsonValueKind.Null)];

        if (retained.Count == members.Count || retained.Count == 0)
        {
            return false;
        }

        schema.Enum = retained;
        return true;
    }
}
