// <auto-generated />
// ==================================================================================================
//  20260101000000_InitialCreate.Designer.cs - THE GENERATED DESIGNER HALF OF THE ONE MIGRATION
//
//  It does exactly two jobs. It makes the migration discoverable by id, through the [Migration]
//  attribute below, and it records the model this migration targets so EF Core can diff that model
//  against Data/Migrations/PowerFrameworkDbContextModelSnapshot.cs. It carries no Up, no Down, no
//  branch, no helper and no computed value: those live in the sibling 20260101000000_InitialCreate.cs,
//  which is the other half of this same partial class. Nothing here needs test coverage because
//  nothing here is hand-written logic.
//
//  THE MODEL IS MIRRORED, NEVER RE-DERIVED
//  ------------------------------------------------------------------------------------------------
//  The single source of truth for every token below is OnModelCreating in
//  Data/PowerFrameworkDbContext.cs. This file mirrors that configuration; it does not independently
//  re-derive the schema from the legacy oracle, because two independent derivations drift. The
//  legacy locators cited throughout are therefore VERIFICATION references, not inputs - they are how
//  a reader confirms the mirror is faithful.
//
//  THE ORACLE, READ-ONLY AND CITED ONLY (C-C)
//  ------------------------------------------------------------------------------------------------
//  ws_objects/pfw.tests.pbl.src/w_test_sqlite.srw:L463-L469 is the ONLY DDL anywhere in the
//  544-object legacy estate - seven PowerScript literals joined with the continuation operator
//  inside the CONNECT button's clicked event:
//
//      "CREATE TABLE IF NOT EXISTS COMPANY("     :L463
//      "ID INTEGER PRIMARY KEY NOT NULL,"        :L464   + /*自增列*/
//      "NAME           TEXT    NOT NULL,"        :L465
//      "AGE            INT     NOT NULL,"        :L466
//      "ADDRESS        CHAR(50),"                :L467
//      "SALARY         REAL,"                    :L468
//      "BIRTH          TEXT)"                    :L469
//
//  ws_objects/pfw.tests.pbl.src/dw_sqlite.srd is the only updatable DataWindow in the repository and
//  declares the same six columns a second time, differently. Both files were read as specification
//  and left untouched: never edited, never moved, never reformatted, never copied into this tree.
//
//  THIS IS A GENERATED FILE AND IS TREATED AS ONE
//  ------------------------------------------------------------------------------------------------
//  The body below is what `dotnet ef migrations add ... --output-dir Data/Migrations` emits for the
//  model in Data/PowerFrameworkDbContext.cs on EF Core 10.0.10 / SDK 10.0.302, verified by running
//  the generator and diffing its output. Only comments were added, and only the ones C-K requires.
//  Nothing is restructured, reordered or reformatted, no annotation call is "tidied" and no helper is
//  extracted, so a regeneration diffs cleanly against it. Two departures exist and both are recorded:
//
//    1. The generator's UTF-8 BOM is stripped. The repository-root .editorconfig sets
//       `charset = utf-8`, not `utf-8-bom`, and all 269 other .cs files under shared/ and services/
//       are BOM-free. This is a byte-level departure with no semantic effect.
//    2. The AUTOINCREMENT suppression call is retained rather than omitted. That one is semantic, it
//       is mandatory, and it is explained next.
//
//  WHY THE SUPPRESSION CALL MUST STAY - AN EF CORE 10.0.10 ROUND-TRIP ASYMMETRY
//  ------------------------------------------------------------------------------------------------
//  The legacy key column is `ID INTEGER PRIMARY KEY NOT NULL` [srw:L464] with NO AUTOINCREMENT
//  keyword; it relies on SQLite's implicit INTEGER PRIMARY KEY rowid aliasing. Repository-wide
//  searches for AUTOINCREMENT and for sqlite_sequence both return zero hits. EF Core's SQLite
//  provider, left to convention, emits AUTOINCREMENT for a generated integer key, which creates a
//  sqlite_sequence side table and makes rowids monotonic instead of reusing a deleted rowid. That is
//  an observable schema and behaviour change, so C-B forbids it, and OnModelCreating suppresses it
//  with SetValueGenerationStrategy(SqliteValueGenerationStrategy.None).
//
//  The asymmetry, established by executing the generator rather than by reading its source: EF's
//  snapshot writer treats SqliteValueGenerationStrategy.None as a default and OMITS it, but the
//  snapshot READER interprets that same absence as Sqlite:Autoincrement = true. Measured both ways
//  against this model:
//
//      designer/snapshot WITH the call     -> `migrations add` produces an EMPTY Up and Down
//      designer/snapshot WITHOUT the call  -> `migrations add` produces a SPURIOUS diff,
//                                             AlterColumn "ID" ... OldAnnotation("Sqlite:Autoincrement", true)
//
//  So the literal generator output does NOT round-trip, and accepting it would let the very next
//  `migrations add` reintroduce AUTOINCREMENT. Retaining the call is what keeps this file, the
//  snapshot and OnModelCreating in agreement. DO NOT DELETE IT as redundant - it is load-bearing.
//
//  THE MODEL RECORDED BELOW
//  ------------------------------------------------------------------------------------------------
//  One entity type, one table, six properties. COMPANY is the only table with DDL evidence, so no
//  second entity may ever appear here (C-E).
//
//      property   column     column type   required   CLR type    DDL locator
//      --------   --------   -----------   --------   ---------   -----------
//      Id         ID         INTEGER       yes, key   long        srw:L464
//      Name       NAME       TEXT          yes        string      srw:L465
//      Age        AGE        INT           yes        long        srw:L466
//      Address    ADDRESS    CHAR(50)      no         string?     srw:L467
//      Salary     SALARY     REAL          no         double?     srw:L468
//      Birth      BIRTH      TEXT          no         string?     srw:L469
//
//  AGE is INT and not INTEGER. The two share an affinity in SQLite, but the token is preserved
//  because the DDL wrote INT. Only Name carries .IsRequired(): Id and Age are non-nullable value
//  types, from which EF infers requiredness, so the generator emits no call for them.
//
//  TWO DIFFERENT ORDERS, BOTH CORRECT, WHICH IS WORTH KNOWING BEFORE "FIXING" EITHER
//  ------------------------------------------------------------------------------------------------
//  Properties appear below as Id, Address, Age, Birth, Name, Salary. That is the generator's own
//  canonical model order - primary key first, then ordinal-alphabetical - and it is a serialization
//  order only. The PHYSICAL column order is set by CreateTable in the sibling migration and is the
//  DDL order ID, NAME, AGE, ADDRESS, SALARY, BIRTH, which EF derives from the CLR declaration order
//  in Data/CompanyEntity.cs with the key hoisted. The physical order is a wire contract:
//  dw_sqlite.srd:L14 retrieves with "SELECT * FROM COMPANY" and :L21-L26 bind DataWindow column ids
//  1 through 6 BY POSITION, so a table built in any other order binds every value to the wrong
//  column. Verified by reading the applied schema back: ID, NAME, AGE, ADDRESS, SALARY, BIRTH.
//
//  FOUR PRESERVED TYPE DIVERGENCES - THE DDL WINS IN EVERY CASE (C-B)
//  ------------------------------------------------------------------------------------------------
//  The DataWindow declares four of these columns differently from the DDL. Each divergence is a
//  defect this port preserves rather than reconciles, because the difference is observable in stored
//  and returned values and reconciling either side would silently invalidate every characterization
//  recording taken against this fixture:
//
//      NAME     DataWindow char(100) [srd:L9]  vs DDL TEXT     [srw:L465] -> unbounded, no length bound
//      ADDRESS  DataWindow char(200) [srd:L11] vs DDL CHAR(50) [srw:L467] -> CHAR(50), no length bound
//      SALARY   DataWindow decimal(2)[srd:L12] vs DDL REAL     [srw:L468] -> REAL/double?, no precision
//      BIRTH    DataWindow date      [srd:L13] vs DDL TEXT     [srw:L469] -> TEXT/string?, no converter
//
//  Preserved deliberately as well: the DataWindow's dbname values are lowercase [srd:L8-L13] while
//  the DDL and this model use uppercase. SQLite identifiers are ASCII-case-insensitive so both
//  resolve, and the inter-layer divergence stands. Do not harmonize it.
//
//  DELIBERATELY ABSENT, EACH FOR A STATED REASON
//  ------------------------------------------------------------------------------------------------
//    * No index, unique constraint, alternate key, check constraint, default value, foreign key,
//      collation, computed column, value converter, query filter, precision or max length. None is
//      configured by OnModelCreating, so recording one here would describe a model that does not
//      exist. In particular dw_sqlite.srd:L14's sort="age A salary A " is a DataWindow-side sort, not
//      a database index, and none is inferred from it - repository-wide searches for CREATE INDEX and
//      CREATE UNIQUE return zero hits, which is positive evidence rather than an assumption.
//    * No seed data, no schema create-or-delete helper call, no table drop and no truncation of any
//      kind. Migrations here are additive only, and this file is a classic place a "helpful" seed row
//      gets slipped in. Paired characterization captures for one workflow id must run against the same
//      persistence-db volume state, neither recreated nor reseeded between the legacy-side and
//      target-side runs, or the recordings are not comparable. The legacy harness does the opposite -
//      w_test_sqlite.srw:L450 calls FileDelete("test.db") before every connect - and nothing
//      equivalent is reproduced.
//    * No connection string, file name, password, key or token (C-F). A designer file is a classic
//      place such a literal leaks in, and none is needed: the design-time factory in
//      Data/PowerFrameworkDbContext.cs calls UseSqlite() with no arguments precisely so the tooling
//      requires no literal.
//    * No SQL Server or Oracle annotation, and no encrypted-SQLite artifact of any kind - no key or
//      encryption pragma (C-E). The legacy enumerates only DBT_MSSQL and DBT_ORACLE and omits SQLite
//      entirely, yet neither dialect has a schema, connection string or line of DDL anywhere in the
//      repository; both survive as pure string transforms under Sql/Paging/. Encrypted SQLite is out
//      of Phase-1 scope, because the shipped encryption library is materially older than the plain one
//      and its key-derivation and per-page-integrity options are unreachable through any framework
//      API. The managed native comes solely from the centrally pinned SQLitePCLRaw.bundle_e_sqlite3,
//      never from the read-only legacy sqlite3 binaries, plain or encrypted.
//    * No package reference is added by this file, and none is needed: Microsoft.EntityFrameworkCore.Design
//      is already one of the exactly six declared in PowerFramework.Persistence.csproj (C-I).
//    * No C# constant, and so no SCREAMING_SNAKE identifier. The preserved COMPANY and column
//      spellings appear as string literals in model-builder calls, which raises no naming diagnostic -
//      no migration file is on the .editorconfig roster carrying those relaxations, and none is needed.
//    * Nothing referencing a deferred capability area (C-D).
//
//  RULES POSITION: no user rules exist for this project. review_rules returns exactly one line
//  saying so, verified directly rather than assumed. Their absence is not licence to lower the bar -
//  the enterprise-standard baseline and the named non-rule constraints C-A through C-L bind in their
//  place and are honoured here exactly as rules would be.
// ==================================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerFramework.Persistence.Data;

#nullable disable

namespace PowerFramework.Persistence.Data.Migrations
{
    [DbContext(typeof(PowerFrameworkDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PowerFramework.Persistence.Data.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .Metadata.SetValueGenerationStrategy(SqliteValueGenerationStrategy.None);

                    b.Property<string>("Address")
                        .HasColumnType("CHAR(50)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("Age")
                        .HasColumnType("INT")
                        .HasColumnName("AGE");

                    b.Property<string>("Birth")
                        .HasColumnType("TEXT")
                        .HasColumnName("BIRTH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<double?>("Salary")
                        .HasColumnType("REAL")
                        .HasColumnName("SALARY");

                    b.HasKey("Id");

                    b.ToTable("COMPANY", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
