// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerFramework.Persistence.Data;

#nullable disable

namespace PowerFramework.Persistence.Data.Migrations
{
    [DbContext(typeof(PowerFrameworkDbContext))]
    partial class PowerFrameworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PowerFramework.Persistence.Data.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .Metadata.SetValueGenerationStrategy(SqliteValueGenerationStrategy.None);

                    b.Property<string>("Address")
                        .HasColumnType("CHAR(50)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("Age")
                        .HasColumnType("INT")
                        .HasColumnName("AGE");

                    b.Property<string>("Birth")
                        .HasColumnType("TEXT")
                        .HasColumnName("BIRTH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<double?>("Salary")
                        .HasColumnType("REAL")
                        .HasColumnName("SALARY");

                    b.HasKey("Id");

                    b.ToTable("COMPANY", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
