// <auto-generated />
// ==================================================================================================
//  PowerFrameworkDbContextModelSnapshot.cs - EF Core's CUMULATIVE record of the current model, and
//  the baseline every future `dotnet ef migrations add` diffs against to compute the next migration.
//
//  This file has exactly one job: agree with OnModelCreating in Data/PowerFrameworkDbContext.cs. Its
//  DISAGREEMENT with that method is the named failure mode of this folder, because a snapshot that
//  records a TIDIER model than the context configures makes the next `migrations add` emit a
//  schema-ALTERING migration that silently corrects a preserved defect - precisely what constraint
//  C-B (no behaviour improvement) exists to prevent. There is no timestamp in the file name: a
//  snapshot is singular and cumulative, unlike the timestamped migration pair beside it.
//
//  MIRRORED FROM THE CONTEXT, NEVER RE-DERIVED FROM THE LEGACY
//  ------------------------------------------------------------------------------------------------
//  Every token below comes from OnModelCreating. The legacy locators cited are VERIFICATION
//  references, not inputs - two independent derivations drift, and drift here IS the spurious diff.
//  The oracle is ws_objects/pfw.tests.pbl.src/w_test_sqlite.srw:L463-L469, the only DDL in the
//  544-object legacy estate, together with ws_objects/pfw.tests.pbl.src/dw_sqlite.srd, the only
//  updatable DataWindow in the repository. Both were read as specification and left untouched:
//  never edited, never moved, never reformatted, never copied into this tree (C-C).
//
//  TWO DEPARTURES FROM THE LITERAL GENERATOR OUTPUT, BOTH MEASURED BY RUNNING THE GENERATOR ON THIS
//  HOST (SDK 10.0.302, EF Core 10.0.10) RATHER THAN BY READING ITS SOURCE - RECORDED BECAUSE C-K
//  REQUIRES EVERY TECHNOLOGY-SPECIFIC DECISION TO BE DOCUMENTED WHERE IT IS MADE
//  ------------------------------------------------------------------------------------------------
//    1. The generator's UTF-8 byte-order mark is stripped. The repository-root .editorconfig sets
//       `charset = utf-8`, not the byte-order-marked variant, and both sibling files in this folder
//       are free of it. Byte-level only, with no semantic effect.
//
//    2. The value-generation call on Id is RETAINED where the generator omits it. This one is
//       semantic, it is mandatory, and it is the single line here that a regeneration must have
//       restored by hand. EF's snapshot WRITER treats SqliteValueGenerationStrategy.None as a
//       default and drops it; the snapshot READER interprets that same absence as
//       Sqlite:Autoincrement = true. Both directions were measured against this exact model:
//
//           snapshot WITH the call     -> `migrations add` yields an EMPTY Up and Down
//           snapshot WITHOUT the call  -> `migrations add` yields
//                                         AlterColumn "ID" ... OldAnnotation("Sqlite:Autoincrement",
//                                         true), so the very next migration REINTRODUCES the keyword
//
//  WHY THAT KEYWORD IS FORBIDDEN. The legacy key column is `ID INTEGER PRIMARY KEY NOT NULL`
//  [srw:L464] with no AUTOINCREMENT keyword - repository-wide searches for it and for sqlite_sequence
//  both return zero hits - and it relies on SQLite's implicit INTEGER PRIMARY KEY rowid aliasing.
//  The keyword would add a sqlite_sequence side table the legacy schema does not have and make rowids
//  monotonic instead of reusing a deleted one: an observable schema AND behaviour change (C-B).
//
//  THE MODEL RECORDED, AND THE FOUR PRESERVED TYPE DIVERGENCES - THE DDL WINS IN EVERY CASE (C-B)
//  ------------------------------------------------------------------------------------------------
//      property  column   type      required  CLR      DataWindow disagreement       DDL locator
//      --------  -------  --------  --------  -------  ----------------------------  -----------
//      Id        ID       INTEGER   yes, key  long     -                             srw:L464
//      Name      NAME     TEXT      yes       string   char(100) [srd:L9] unbounded  srw:L465
//      Age       AGE      INT       yes       long     -                             srw:L466
//      Address   ADDRESS  CHAR(50)  no        string?  char(200) [srd:L11] 50 kept   srw:L467
//      Salary    SALARY   REAL      no        double?  decimal(2) [srd:L12] -> REAL  srw:L468
//      Birth     BIRTH    TEXT      no        string?  date [srd:L13] -> TEXT        srw:L469
//
//  AGE is INT and not INTEGER: affinity-equivalent to SQLite, but the DDL wrote INT, so the token is
//  preserved. Only Name carries a requiredness call - Id and Age are non-nullable value types, from
//  which EF infers it. The DataWindow's dbname spellings are lowercase [srd:L8-L13] against this
//  model's uppercase; SQLite compares ASCII identifiers case-insensitively, so both resolve and the
//  inter-layer divergence stands unharmonized.
//
//  TWO ORDERS, BOTH CORRECT, WHICH IS WORTH KNOWING BEFORE "FIXING" EITHER
//  ------------------------------------------------------------------------------------------------
//  Properties appear below as Id, Address, Age, Birth, Name, Salary - the generator's own canonical
//  serialization order, key first then alphabetical. The PHYSICAL column order is ID, NAME, AGE,
//  ADDRESS, SALARY, BIRTH, set by CreateTable in 20260101000000_InitialCreate.cs from the CLR
//  declaration order in Data/CompanyEntity.cs. That physical order is a wire contract: srd:L14
//  retrieves with "SELECT * FROM COMPANY" and srd:L21-L26 bind DataWindow column ids 1 through 6 BY
//  POSITION, so a table built in any other order binds every value to the wrong column.
//
//  DELIBERATELY ABSENT, BECAUSE OnModelCreating CONFIGURES NONE OF IT
//  ------------------------------------------------------------------------------------------------
//  Recording a model that does not exist is the whole failure mode, so nothing is added that EF might
//  "normally" infer: no index - srd:L14's sort="age A salary A " is a DataWindow-side sort and creates
//  no database index, and repository-wide searches for index-creating statements return zero hits - no
//  unique or check constraint, no alternate key, no foreign key, no maximum length, no precision or
//  scale, no default value, no computed column, no collation, no value converter, no query filter and
//  no concurrency token. On that last point: updatewhere=1 [srd:L14] compares the key plus the
//  ORIGINAL values of all six updateable columns, and that predicate is rebuilt at runtime by
//  Concurrency/UpdateWhereBuilder.cs; an EF token would replace it with a different predicate over a
//  column the DDL does not have. Also absent: seed data, any create-or-delete helper, any table drop,
//  any truncation, any second entity type (C-E), any SQL Server or Oracle annotation - the legacy
//  enumerates only those two engines and omits SQLite altogether, yet neither has a schema or a line
//  of DDL anywhere, so both survive as pure string transforms under Sql/Paging/ - any encrypted-SQLite
//  artifact or encryption directive, any connection string, file path, password or token (C-F), any
//  package reference (C-I), any C# constant and therefore any SCREAMING_SNAKE identifier, and anything
//  belonging to a deferred capability area (C-D). Absent too is hand-written logic of any kind: there
//  is no branch, no loop, no computed value and no helper here, so nothing in this file needs test
//  coverage and the per-service line-coverage gate is not dragged by it (C-H).
//
//  Seed data deserves its own sentence because it is the easiest thing to add "helpfully" and the
//  worst to add here: it would drive insert operations on a future `migrations add`. Paired
//  characterization captures for one workflow identifier must run against the same persistence-db
//  volume state, neither recreated nor reseeded between the legacy-side and target-side runs, or the
//  recordings are not comparable at all (C-J). The legacy harness does the opposite -
//  w_test_sqlite.srw:L450 destroys the database file before every connect - and nothing equivalent is
//  reproduced anywhere in this service.
//
//  RULES POSITION: no user rules exist for this project. review_rules returns exactly one line saying
//  so, verified directly rather than assumed. Their absence lowers nothing - the enterprise-standard
//  baseline and the named non-rule constraints C-A through C-L bind in their place and are honoured
//  here exactly as rules would be.
// ==================================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerFramework.Persistence.Data;

#nullable disable

namespace PowerFramework.Persistence.Data.Migrations
{
    [DbContext(typeof(PowerFrameworkDbContext))]
    partial class PowerFrameworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PowerFramework.Persistence.Data.CompanyEntity", b =>
                {
                    // The last call in this chain is the AUTOINCREMENT suppression and it is
                    // LOAD-BEARING. DO NOT DELETE IT as redundant just because the generator omits
                    // it: without it the snapshot reader infers Sqlite:Autoincrement = true and the
                    // next `migrations add` emits an AlterColumn that reintroduces the keyword. Both
                    // outcomes were measured; see the header.
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .Metadata.SetValueGenerationStrategy(SqliteValueGenerationStrategy.None);

                    b.Property<string>("Address")
                        .HasColumnType("CHAR(50)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("Age")
                        .HasColumnType("INT")
                        .HasColumnName("AGE");

                    b.Property<string>("Birth")
                        .HasColumnType("TEXT")
                        .HasColumnName("BIRTH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<double?>("Salary")
                        .HasColumnType("REAL")
                        .HasColumnName("SALARY");

                    b.HasKey("Id");

                    b.ToTable("COMPANY", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
